---
last_updated: 2025-12-19
project: LLM Resource Sizer
type: Enterprise AI Infrastructure Decision Hub
stack: Vanilla JavaScript, GitHub Actions, Node.js (Build-time), HTML5, CSS3

core_files:
  - index.html: Main calculator entry point
  - models/index.html: Model Explorer database
  - hardware/index.html: Hardware Hub overview
  - js/ui.js: Core UI logic, i18n, and dynamic data binding
  - js/calc.js: Physics-based calculation engine
  - scripts/fetch-models.js: Automated Hugging Face data pipeline
  - data/models.json: Auto-updated model specifications (93+ models)
  - data/hardware/*.json: Verified NVIDIA and Huawei hardware specs

data_schema:
  models:
    source: scripts/fetch-models.js
    storage: data/models.json
    fields: [id, name, parameters_billion, architecture, hidden_size, num_layers, moe_num_experts, moe_top_k]
  hardware:
    source: Manual curation (verified sources)
    storage: data/hardware/{vendor}.json
    fields: [id, name, vram_gb, bandwidth_gbps, fp16_tflops, bf16_tflops, max_cards_per_node]

interconnected_pages:
  - persona_guides: [/for/enterprise.html, /for/teams.html, /for/researchers.html, /for/hobbyists.html]
  - vendor_pages: [/hardware/nvidia.html, /hardware/huawei.html]

pipeline:
  trigger: GitHub Actions (Weekly / Manual)
  logic: Fetch HF API -> Filter 80B+ Open Source -> Estimate/Parse Params -> JSON Output
